### ISSUE TITLE
Problem in blender 4

### ISSUE THREAD

**Issue by b4zz4** [sketchy-squirrel/smart-bones#2]
```
Python: Traceback (most recent call last):
../blender-smart-bones.py", line 266, in execute
    current_selection.append(armature_data.layers[i])
                             ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Armature' object has no attribute 'layers'
```

**Comment by sketchy-squirrel** [comment]
Hey there, thanks for bringing this to my attention. Sorry it took so long, but I've updated the code, let me know if it works for you. 👍

**Comment by b4zz4** [comment]
I think it's not working. As you see the action, the control bone and does not create the action inside the bone

https://github.com/sketchy-squirrel/smart-bones/assets/643833/d5d3a8e9-64ac-4afc-930b-eafae9628b89

**Comment by sketchy-squirrel** [comment]
That is strange. Could you send me your blender file? Thank you

**Comment by b4zz4** [comment]
I don't have time, I'll rearrange it later and pass it to you. It's just a skeleton with an action and a bucket.
